joint_1:
  x: 0
  y: 0
  z: 0
  roll: 0
  pitch: 0
  yaw: 0
joint_2:
  x: 0
  y: 0
  z: 0
  roll: 0
  pitch: 0
  yaw: 0
joint_3:
  x: 0
  y: 0
  z: 0
  roll: 0
  pitch: 0
  yaw: 0
joint_4:
  x: 0
  y: 0
  z: 0
  roll: 0
  pitch: 0
  yaw: 0
joint_5:
  x: 0
  y: 0
  z: 0
  roll: 0
  pitch: 0
  yaw: 0
joint_6:
  x: 0
  y: 0
  z: 0
  roll: 0
  pitch: 0
  yaw: 0
joint_7:
  x: 0
  y: 0
  z: 0
  roll: 0
  pitch: 0
  yaw: 0